pipeline{
    agent any

    environment {
        GIT_REPO_URL = "https://github.com/gachips/sample.git"
        BRANCH = "main"
    }
    cleanWs()
    stages{
        stage('checkout'){
            steps{
                echo "checkout source code"
                git branch: "${BRANCH}", url: "${GIT_REPO_URL}"
            }
        }

        stage ('build'){
            steps{
                echo "build the project"
                cd project
                echo "present working "
                sh 'pwd'
                sh 'mvn clean package'
            }
        }

        stage('Archive Artifacts'){
            steps{
                echo "Archiving the build artifacts"
                archiveArtifacts artifacts: 'target/*.jar', fingerprint: true
            }
        }
    }
    post {
        success {
            echo "Build is success"
        }
        failure {
            echo "Build is Failed!"
        }
    }
}
